-- =====================================================================
-- RedEconómica v1.0.0 — Datos semilla del Valle Económico
-- =====================================================================
-- Generado por tools/generar_sample_data.py a partir de data/seed/*.kt
-- Es exactamente el contenido que DatabaseSeeder escribe en el primer
-- arranque de la app. Al final hay unas filas de ESTADO de ejemplo para
-- ilustrar cómo queda la base de datos tras un rato de juego.
-- =====================================================================

-- ------------------------------ recursos (20) ------------------------------
INSERT INTO resources (id, singular, plural, tipo, valorBase, descripcion) VALUES ('manzana', 'manzana', 'manzanas', 'ALIMENTO', 1, 'Fruta del huerto de Lía. Se recoge rápido y gusta a todo el mundo.');
INSERT INTO resources (id, singular, plural, tipo, valorBase, descripcion) VALUES ('verdura', 'verdura', 'verduras', 'ALIMENTO', 1, 'Lo que sale de la tierra del Valle: zanahorias, calabazas, judías.');
INSERT INTO resources (id, singular, plural, tipo, valorBase, descripcion) VALUES ('trigo', 'saco de trigo', 'sacos de trigo', 'MATERIA_PRIMA', 1, 'El grano del campo. Todavía no se puede comer así.');
INSERT INTO resources (id, singular, plural, tipo, valorBase, descripcion) VALUES ('harina', 'saco de harina', 'sacos de harina', 'ELABORADO', 2, 'Trigo molido. Es el paso intermedio para el pan.');
INSERT INTO resources (id, singular, plural, tipo, valorBase, descripcion) VALUES ('pan', 'pan', 'panes', 'ELABORADO', 2, 'Sale del horno de Tomás. Todo el Valle lo busca.');
INSERT INTO resources (id, singular, plural, tipo, valorBase, descripcion) VALUES ('pescado', 'pescado', 'pescados', 'ALIMENTO', 2, 'Del río del Valle. Hay que ir temprano.');
INSERT INTO resources (id, singular, plural, tipo, valorBase, descripcion) VALUES ('leche', 'jarra de leche', 'jarras de leche', 'ALIMENTO', 1, 'De las cabras del prado alto.');
INSERT INTO resources (id, singular, plural, tipo, valorBase, descripcion) VALUES ('queso', 'queso', 'quesos', 'ELABORADO', 2, 'Leche que ha esperado unas semanas. Merece la pena.');
INSERT INTO resources (id, singular, plural, tipo, valorBase, descripcion) VALUES ('miel', 'tarro de miel', 'tarros de miel', 'ALIMENTO', 2, 'De las colmenas del bosque. Poca cantidad, mucha demanda.');
INSERT INTO resources (id, singular, plural, tipo, valorBase, descripcion) VALUES ('madera', 'tronco', 'troncos', 'MATERIA_PRIMA', 1, 'Del bosque de arriba. Pesa, pero sirve para casi todo.');
INSERT INTO resources (id, singular, plural, tipo, valorBase, descripcion) VALUES ('tabla', 'tabla', 'tablas', 'ELABORADO', 2, 'Madera ya cortada y lista para construir.');
INSERT INTO resources (id, singular, plural, tipo, valorBase, descripcion) VALUES ('mesa', 'mesa', 'mesas', 'ELABORADO', 4, 'Cuesta mucha madera y mucho trabajo, pero dura años.');
INSERT INTO resources (id, singular, plural, tipo, valorBase, descripcion) VALUES ('silla', 'silla', 'sillas', 'ELABORADO', 3, 'Más pequeña que una mesa, y hacen falta varias.');
INSERT INTO resources (id, singular, plural, tipo, valorBase, descripcion) VALUES ('herramienta', 'herramienta', 'herramientas', 'HERRAMIENTA', 3, 'Martillos, azadas y sierras del taller de Sofía.');
INSERT INTO resources (id, singular, plural, tipo, valorBase, descripcion) VALUES ('clavo', 'puñado de clavos', 'puñados de clavos', 'HERRAMIENTA', 1, 'Pequeños, baratos y siempre faltan justo al final.');
INSERT INTO resources (id, singular, plural, tipo, valorBase, descripcion) VALUES ('lana', 'vellón de lana', 'vellones de lana', 'MATERIA_PRIMA', 1, 'De las ovejas del prado. Hay que lavarla y peinarla.');
INSERT INTO resources (id, singular, plural, tipo, valorBase, descripcion) VALUES ('tela', 'tela', 'telas', 'TEXTIL', 2, 'Lana convertida en algo que ya se puede usar.');
INSERT INTO resources (id, singular, plural, tipo, valorBase, descripcion) VALUES ('manta', 'manta', 'mantas', 'TEXTIL', 3, 'Abriga de verdad. En invierno el Valle no habla de otra cosa.');
INSERT INTO resources (id, singular, plural, tipo, valorBase, descripcion) VALUES ('semilla', 'puñado de semillas', 'puñados de semillas', 'MATERIA_PRIMA', 1, 'Lo que hay que sembrar hoy para tener comida mañana.');
INSERT INTO resources (id, singular, plural, tipo, valorBase, descripcion) VALUES ('cesta', 'cesta', 'cestas', 'ELABORADO', 2, 'Sin cestas, media cosecha se queda en el campo.');

-- ---------------------------- habitantes -----------------------------
INSERT INTO characters (id, nombre, oficio, lugar, presentacion, productividad, inventarioBase, avatarId, esGuia) VALUES ('lia', 'Lía', 'Fruticultora', 'GRANJA', 'Sube al frutal antes que salga el sol. Recoge manzanas más rápido que nadie, pero el horno se le da fatal.', 'manzana:6|miel:2|semilla:2|verdura:3', 'manzana:6', 'lia', 0);
INSERT INTO characters (id, nombre, oficio, lugar, presentacion, productividad, inventarioBase, avatarId, esGuia) VALUES ('tomas', 'Tomás', 'Panadero', 'PANADERIA', 'Enciende el horno de madrugada. Convierte harina en pan como nadie, aunque nunca ha sabido plantar nada.', 'harina:4|pan:5|trigo:2', 'pan:5', 'tomas', 0);
INSERT INTO characters (id, nombre, oficio, lugar, presentacion, productividad, inventarioBase, avatarId, esGuia) VALUES ('nina', 'Nina', 'Carpintera', 'CARPINTERIA', 'Su taller huele a serrín. Con un tronco y tiempo saca tablas, sillas y hasta mesas.', 'madera:5|mesa:2|silla:3|tabla:4', 'madera:5|tabla:2', 'nina', 0);
INSERT INTO characters (id, nombre, oficio, lugar, presentacion, productividad, inventarioBase, avatarId, esGuia) VALUES ('bruno', 'Bruno', 'Hortelano', 'HUERTO', 'Habla con sus tomates. Del huerto salen verduras todo el año, pero sus herramientas están hechas polvo.', 'manzana:2|semilla:4|trigo:3|verdura:6', 'semilla:3|verdura:6', 'bruno', 0);
INSERT INTO characters (id, nombre, oficio, lugar, presentacion, productividad, inventarioBase, avatarId, esGuia) VALUES ('sofia', 'Sofía', 'Herrera', 'TALLER', 'Golpea el metal con una calma que asusta. Hace herramientas que duran una vida.', 'clavo:6|herramienta:4|tabla:2', 'clavo:4|herramienta:3', 'sofia', 0);
INSERT INTO characters (id, nombre, oficio, lugar, presentacion, productividad, inventarioBase, avatarId, esGuia) VALUES ('emi', 'Emi', 'Pescadora', 'PESQUERIA', 'Conoce cada recodo del río. Vuelve con la cesta llena y con historias que nadie se cree.', 'cesta:3|madera:2|pescado:5', 'cesta:2|pescado:5', 'emi', 0);
INSERT INTO characters (id, nombre, oficio, lugar, presentacion, productividad, inventarioBase, avatarId, esGuia) VALUES ('dani', 'Dani', 'Tejedor', 'TELAR', 'Su telar suena todo el día. De la lana saca telas, y de las telas mantas para el invierno.', 'lana:5|manta:2|tela:4', 'lana:3|tela:4', 'dani', 0);
INSERT INTO characters (id, nombre, oficio, lugar, presentacion, productividad, inventarioBase, avatarId, esGuia) VALUES ('rita', 'Rita', 'Transportista', 'MERCADO', 'Con su carreta cruza el Valle dos veces al día. No produce casi nada, pero sin ella nada llega.', 'cesta:4|leche:3|queso:2', 'cesta:2|leche:4|queso:2', 'rita', 0);
INSERT INTO characters (id, nombre, oficio, lugar, presentacion, productividad, inventarioBase, avatarId, esGuia) VALUES ('tilo', 'Tilo', 'Cartero del Valle', 'PLAZA', 'Un zorro con bandolera que lleva y trae recados. Sabe quién necesita qué antes que nadie.', '', '', 'tilo', 1);

-- ----------------------------- misiones ------------------------------
INSERT INTO missions (id, numero, titulo, lugar, concepto, narrativaInicio, narrativaFinal, objetivoVisible, requiereMision, insigniaId, zonaDesbloqueada, sellos) VALUES ('m01', 1, 'La primera cosecha', 'GRANJA', 'NECESIDADES', 'Acabas de llegar al Valle. Tilo, el zorro cartero, te deja una nota: «Empieza por la granja de Lía. Verás que aquí nadie necesita lo mismo».', 'Ya sabes lo primero: cada vecino necesita cosas distintas, y para conseguirlas alguien tiene que producirlas.', 'Ayuda a Lía a recoger y a repartir la primera cosecha', NULL, NULL, 'MERCADO', 3);
INSERT INTO missions (id, numero, titulo, lugar, concepto, narrativaInicio, narrativaFinal, objetivoVisible, requiereMision, insigniaId, zonaDesbloqueada, sellos) VALUES ('m02', 2, '¿Quién tiene lo que necesito?', 'MERCADO', 'INTERCAMBIO', '«Tienes manzanas y te falta pan», dice Tilo. «En el Valle eso tiene arreglo. Baja a la plaza».', 'Has hecho tu primer trueque. No hiciste el pan: lo conseguiste dando algo que a otro le faltaba.', 'Consigue pan y herramientas sin producirlos tú', 'm01', 'primer_trato', 'TALLER', 3);
INSERT INTO missions (id, numero, titulo, lugar, concepto, narrativaInicio, narrativaFinal, objetivoVisible, requiereMision, insigniaId, zonaDesbloqueada, sellos) VALUES ('m03', 3, 'Cada uno a lo suyo', 'TALLER', 'ESPECIALIZACION', 'En el Valle todos intentan hacer un poco de todo, y todo sale a medias. Sofía cree que hay otra manera.', 'Concentrarse en una sola tarea produce más que repartirse entre varias. Eso se llama especializarse.', 'Descubre qué pasa cuando cada uno hace una sola cosa', 'm02', 'especialista', 'PLAZA', 4);
INSERT INTO missions (id, numero, titulo, lugar, concepto, narrativaInicio, narrativaFinal, objetivoVisible, requiereMision, insigniaId, zonaDesbloqueada, sellos) VALUES ('m04', 4, 'Intercambio de vecinos', 'PLAZA', 'INTERCAMBIO', 'La plaza se ha llenado. Hoy no basta con un trato: hacen falta varios, y no todo el mundo puede desprenderse de lo suyo.', 'Un intercambio depende de lo que cada persona necesita. Lo que a uno le sobra, a otro le hace falta… y al revés.', 'Resuelve varias necesidades en la misma tarde', 'm03', NULL, 'PANADERIA', 4);
INSERT INTO missions (id, numero, titulo, lugar, concepto, narrativaInicio, narrativaFinal, objetivoVisible, requiereMision, insigniaId, zonaDesbloqueada, sellos) VALUES ('m05', 5, 'El problema del pan', 'PANADERIA', 'RECURSOS', 'El horno se apagó de madrugada. Solo hay tres panes y en la plaza esperan cinco vecinos.', 'Cuando hay menos de lo que hace falta, decimos que hay escasez. Y entonces hay que decidir.', 'Reparte lo poco que hay sin dejar a nadie tirado', 'm04', 'maestro_recursos', 'CARPINTERIA', 4);
INSERT INTO missions (id, numero, titulo, lugar, concepto, narrativaInicio, narrativaFinal, objetivoVisible, requiereMision, insigniaId, zonaDesbloqueada, sellos) VALUES ('m06', 6, 'La gran decisión', 'CARPINTERIA', 'ELECCION', 'Nina ha traído diez troncos. Con eso sale una mesa grande… o varias cosas pequeñas. No las dos.', 'Elegir una cosa es renunciar a otra. A eso se le llama costo de oportunidad, y aparece en cada decisión.', 'Aprende a mirar lo que dejas de hacer', 'm05', 'experto_decisiones', 'TELAR', 5);
INSERT INTO missions (id, numero, titulo, lugar, concepto, narrativaInicio, narrativaFinal, objetivoVisible, requiereMision, insigniaId, zonaDesbloqueada, sellos) VALUES ('m07', 7, 'Juntos podemos', 'TELAR', 'COOPERACION', 'Se acerca el frío y hacen falta mantas. Nadie puede esquilar, tejer y repartir a la vez.', 'Lo que sale al final no es la suma de lo que hace cada uno: es lo que permite la etapa más floja.', 'Organiza el trabajo en equipo del Valle', 'm06', 'constructor_equipos', 'COOPERATIVA', 5);
INSERT INTO missions (id, numero, titulo, lugar, concepto, narrativaInicio, narrativaFinal, objetivoVisible, requiereMision, insigniaId, zonaDesbloqueada, sellos) VALUES ('m08', 8, 'La cooperativa', 'COOPERATIVA', 'COOPERACION', 'Cuatro vecinos han puesto sus recursos en común. Ahora hay que organizarse de verdad.', 'Juntos consiguieron algo que ninguno podía hacer solo. Eso es una cooperativa.', 'Pon en marcha la cooperativa del Valle', 'm07', NULL, 'CENTRO_INTERCAMBIO', 5);
INSERT INTO missions (id, numero, titulo, lugar, concepto, narrativaInicio, narrativaFinal, objetivoVisible, requiereMision, insigniaId, zonaDesbloqueada, sellos) VALUES ('m09', 9, 'El mercado del Valle', 'MERCADO', 'INTEGRACION', 'Día de mercado. Hay puestos, prisas y alguna propuesta que no es tan buena como parece.', 'En el mercado no hay precios escritos: hay personas con necesidades distintas poniéndose de acuerdo.', 'Muévete en el mercado sin que te la cuelen', 'm08', 'gran_negociador', 'LABORATORIO', 6);
INSERT INTO missions (id, numero, titulo, lugar, concepto, narrativaInicio, narrativaFinal, objetivoVisible, requiereMision, insigniaId, zonaDesbloqueada, sellos) VALUES ('m10', 10, 'La gran feria', 'PLAZA', 'INTEGRACION', 'Una vez al año el Valle entero se junta en la plaza. Hay que producir, montar, repartir, decidir e intercambiar. Todo en dos días.', 'Has puesto en marcha una feria entera. Producción, especialización, cooperación, escasez y decisiones: todo junto.', 'Prepara la feria del Valle de principio a fin', 'm09', 'cooperador_valle', 'HUERTO', 8);
INSERT INTO missions (id, numero, titulo, lugar, concepto, narrativaInicio, narrativaFinal, objetivoVisible, requiereMision, insigniaId, zonaDesbloqueada, sellos) VALUES ('m11', 11, 'El taller de los oficios', 'TALLER', 'ESPECIALIZACION', '«Lía es mejor que Bruno en todo», dice alguien en el taller. Tilo levanta una ceja: «¿Seguro que eso lo decide todo?».', 'No siempre produce una cosa quien mejor la hace, sino quien menos pierde al dedicarse a ella.', 'Descubre por qué conviene repartirse el trabajo igualmente', 'm10', NULL, NULL, 6);
INSERT INTO missions (id, numero, titulo, lugar, concepto, narrativaInicio, narrativaFinal, objetivoVisible, requiereMision, insigniaId, zonaDesbloqueada, sellos) VALUES ('m12', 12, 'El invierno se acerca', 'HUERTO', 'ELECCION', 'Las primeras heladas están al caer. Queda poca lana, poca madera y ninguna semana de sobra.', 'El Valle pasó el invierno porque alguien decidió a tiempo qué hacer primero.', 'Prepara el Valle para el frío con lo poco que queda', 'm11', NULL, NULL, 6);
INSERT INTO missions (id, numero, titulo, lugar, concepto, narrativaInicio, narrativaFinal, objetivoVisible, requiereMision, insigniaId, zonaDesbloqueada, sellos) VALUES ('m13', 13, 'Las cadenas del Valle', 'CENTRO_INTERCAMBIO', 'COOPERACION', 'En el Centro de Intercambio guardan un mural con todos los caminos que recorre un producto. Está desordenado.', 'Detrás de cada cosa hay una cadena de personas, y cada una se ocupa de un trozo.', 'Reconstruye las cadenas de producción del Valle', 'm12', NULL, NULL, 5);
INSERT INTO missions (id, numero, titulo, lugar, concepto, narrativaInicio, narrativaFinal, objetivoVisible, requiereMision, insigniaId, zonaDesbloqueada, sellos) VALUES ('m14', 14, 'El Valle entero', 'PLAZA', 'INTEGRACION', 'Último encargo de Tilo antes de cerrar el correo del año. Un turno, cinco oficios y tres cosas por resolver.', 'Llegaste sin saber qué era un intercambio y te vas organizando una economía entera. Ah, y eso que has estado haciendo… se llama economía.', 'Haz funcionar el Valle entero por tu cuenta', 'm13', 'maestro_economia', NULL, 10);

-- ---------------------------- escenarios -----------------------------
INSERT INTO scenarios (id, misionId, orden, tipo, titulo, situacion, instruccion, explicacionFinal, conceptoId, dificultad) VALUES ('s01', 'm01', 0, 'ESPECIALIZACION', 'La primera cosecha', 'Lía tiene el frutal lleno y una mañana entera por delante. El Valle necesita seis manzanas para empezar la semana.', 'Dile a Lía a qué dedica el turno y pulsa «Trabajar».', 'Lía consigue seis manzanas porque dedicó el turno entero al frutal. Cuando reparte el tiempo entre varias tareas, saca menos de cada una.', 'NECESIDADES', 1);
INSERT INTO scenarios (id, misionId, orden, tipo, titulo, situacion, instruccion, explicacionFinal, conceptoId, dificultad) VALUES ('s02', 'm01', 1, 'ESCASEZ', 'Seis manzanas, tres vecinos', 'Tilo ha dejado la cesta de Lía en la plaza. Tomás, Nina y Dani se acercan, y cada uno pide una cantidad distinta.', 'Reparte las seis manzanas según lo que pide cada uno.', 'Cada vecino necesitaba una cantidad distinta. Hoy había justo para todos: eso no siempre pasa.', 'NECESIDADES', 1);
INSERT INTO scenarios (id, misionId, orden, tipo, titulo, situacion, instruccion, explicacionFinal, conceptoId, dificultad) VALUES ('s03', 'm01', 2, 'ESPECIALIZACION', 'Dos huertos, dos manos', 'Lía y Bruno trabajan la misma mañana. El Valle quiere seis manzanas y seis verduras.', 'Asigna una tarea a cada uno y compara con «que cada uno haga de todo».', 'Lía es más rápida con las manzanas y Bruno con las verduras. Si cada uno hace lo suyo, el Valle consigue las dos cosas.', 'RECURSOS', 1);
INSERT INTO scenarios (id, misionId, orden, tipo, titulo, situacion, instruccion, explicacionFinal, conceptoId, dificultad) VALUES ('s04', 'm02', 0, 'INTERCAMBIO', 'El primer trueque', 'Tienes cinco manzanas y ningún pan. Tomás tiene el horno lleno de pan y lleva dos días sin comer fruta.', 'Arrastra lo que ofreces y lo que pides, y propónselo a Tomás.', 'Los dos teníais algo que al otro le faltaba. A eso se le llama intercambio: nadie pierde, los dos ganan lo que necesitaban.', 'INTERCAMBIO', 1);
INSERT INTO scenarios (id, misionId, orden, tipo, titulo, situacion, instruccion, explicacionFinal, conceptoId, dificultad) VALUES ('s05', 'm02', 1, 'EVALUAR_OFERTA', '¿Aceptarías este trato?', 'Rita llega con su carreta y te propone algo. Tú tienes manzanas de sobra, pero lo que buscas es pan.', 'Mira lo que ofrece y lo que pide. ¿Te interesa?', 'La leche está muy bien, pero hoy no te resuelve nada: tú buscabas pan. Un intercambio solo merece la pena si te da algo que necesitas.', 'INTERCAMBIO', 2);
INSERT INTO scenarios (id, misionId, orden, tipo, titulo, situacion, instruccion, explicacionFinal, conceptoId, dificultad) VALUES ('s06', 'm02', 2, 'INTERCAMBIO', 'Herramientas para el huerto', 'Tienes seis verduras recién recogidas. Sofía tiene herramientas colgadas en la pared del taller y hoy no ha comido nada verde.', 'Propón un intercambio que a Sofía le parezca justo.', 'Una herramienta cuesta muchas horas de trabajo; una verdura, muchas menos. Por eso Sofía pide varias verduras por cada herramienta.', 'INTERCAMBIO', 2);
INSERT INTO scenarios (id, misionId, orden, tipo, titulo, situacion, instruccion, explicacionFinal, conceptoId, dificultad) VALUES ('s07', 'm03', 0, 'ESPECIALIZACION', '¿Y si cada uno hace solo una cosa?', 'Lía y Tomás han probado a hacer un poco de todo y el resultado ha sido flojo. Hoy van a intentarlo de otra manera.', 'Prueba primero «que cada uno haga de todo» y luego especializa. Compara.', 'Repartir el turno entre dos tareas no da la mitad de cada una: da menos. Concentrarse en una sola cosa se llama especializarse.', 'ESPECIALIZACION', 2);
INSERT INTO scenarios (id, misionId, orden, tipo, titulo, situacion, instruccion, explicacionFinal, conceptoId, dificultad) VALUES ('s08', 'm03', 1, 'ESPECIALIZACION', 'El encargo del taller', 'Sofía necesita clavos, Nina tablas y en la plaza piden fruta. Tres habitantes, un turno.', 'Decide en qué se especializa cada uno para cubrir el encargo.', 'Cada uno se puso en lo que mejor se le da. El Valle consiguió las tres cosas en el mismo turno.', 'ESPECIALIZACION', 2);
INSERT INTO scenarios (id, misionId, orden, tipo, titulo, situacion, instruccion, explicacionFinal, conceptoId, dificultad) VALUES ('s09', 'm03', 2, 'ESPECIALIZACION', 'El pedido de la escuela', 'La escuela del Valle prepara la comida de la semana: verduras, pan y pescado.', 'Asigna a Bruno, Tomás y Emi. Solo hay un turno.', 'Nadie sabe hacerlo todo, y no hace falta: entre tres personas especializadas sale el pedido completo.', 'ESPECIALIZACION', 3);
INSERT INTO scenarios (id, misionId, orden, tipo, titulo, situacion, instruccion, explicacionFinal, conceptoId, dificultad) VALUES ('s10', 'm04', 0, 'INTERCAMBIO', 'Dos tratos en la plaza', 'Se acerca la noche y necesitas pan para cenar y una tela para la ventana. Tienes seis manzanas y dos vecinos con hambre de fruta.', 'Haz los intercambios que hagan falta hasta conseguir las dos cosas.', 'Con las mismas manzanas has resuelto dos necesidades distintas, porque cada vecino quería algo diferente.', 'INTERCAMBIO', 3);
INSERT INTO scenarios (id, misionId, orden, tipo, titulo, situacion, instruccion, explicacionFinal, conceptoId, dificultad) VALUES ('s11', 'm04', 1, 'EVALUAR_OFERTA', 'La propuesta de Nina', 'Estás arreglando un banco y te faltan dos tablas. Nina aparece con ellas justo cuando tienes el cesto lleno de manzanas.', 'Decide si aceptas la propuesta de Nina.', 'Este sí: Nina se queda con la fruta que le faltaba y tú con las tablas que necesitabas. Los dos salís ganando.', 'INTERCAMBIO', 2);
INSERT INTO scenarios (id, misionId, orden, tipo, titulo, situacion, instruccion, explicacionFinal, conceptoId, dificultad) VALUES ('s12', 'm04', 2, 'INTERCAMBIO', 'Pídele lo que le sobra', 'Vuelves del río con cuatro pescados. Lía tiene dos panes, pero son justo los que necesita para mañana. Tomás también tiene pan… y lleva días sin pescado.', 'Consigue dos panes sin dejar a nadie sin lo que necesita.', 'A Lía el pan no le sobra: es justo el que necesita. Tomás sí puede desprenderse del suyo. Por eso un intercambio depende de lo que cada uno necesita.', 'INTERCAMBIO', 3);
INSERT INTO scenarios (id, misionId, orden, tipo, titulo, situacion, instruccion, explicacionFinal, conceptoId, dificultad) VALUES ('s13', 'm05', 0, 'ESCASEZ', 'El problema del pan', 'El horno se apagó a media noche y solo han salido tres panes. En la plaza hay cinco vecinos esperando.', 'Reparte los tres panes. No hay para todos: piensa a quién le hace más falta.', 'Se pedían siete panes y solo había tres. Cuando hay menos de lo que hace falta, decimos que hay escasez, y alguien tiene que quedarse con menos.', 'RECURSOS', 3);
INSERT INTO scenarios (id, misionId, orden, tipo, titulo, situacion, instruccion, explicacionFinal, conceptoId, dificultad) VALUES ('s14', 'm05', 1, 'ESCASEZ', 'Cuatro herramientas', 'Sofía ha terminado cuatro herramientas esta semana. Cuatro vecinos las quieren, y entre todos piden seis.', 'Reparte las cuatro herramientas. Hay más de una forma razonable de hacerlo.', 'Aquí no había una única respuesta correcta. Lo importante era atender primero a quien no podía esperar y repartir el resto con cabeza.', 'RECURSOS', 3);
INSERT INTO scenarios (id, misionId, orden, tipo, titulo, situacion, instruccion, explicacionFinal, conceptoId, dificultad) VALUES ('s15', 'm05', 2, 'DECISION', 'Cinco sacos de trigo', 'En el granero quedan cinco sacos de trigo. Se puede moler, se puede guardar para sembrar, o se puede preparar la fiesta del Valle. No da para todo.', 'Elige como mucho dos cosas y mira a qué renuncias.', 'Con cinco sacos no cabía todo. Al elegir una cosa dejaste de tener otra: eso pasa siempre que los recursos son limitados.', 'ELECCION', 3);
INSERT INTO scenarios (id, misionId, orden, tipo, titulo, situacion, instruccion, explicacionFinal, conceptoId, dificultad) VALUES ('s16', 'm06', 0, 'DECISION', 'Diez troncos', 'Nina ha traído diez troncos del bosque. Con eso puede salir una mesa grande, o unas cuantas cosas más pequeñas. No las dos.', 'Elige como mucho dos cosas y observa a qué renuncias.', 'Los troncos eran limitados. Cada cosa que elegiste te dejó sin otra: a eso lo llamamos elegir, y siempre tiene un precio.', 'ELECCION', 3);
INSERT INTO scenarios (id, misionId, orden, tipo, titulo, situacion, instruccion, explicacionFinal, conceptoId, dificultad) VALUES ('s17', 'm06', 1, 'COSTO_OPORTUNIDAD', 'Lo que Lía deja de hacer', 'En un turno Lía puede recoger seis manzanas o cuidar tres verduras. Hoy se ha ido al frutal con la cesta grande.', 'Si dedica el turno entero a las manzanas, ¿cuántas verduras deja de conseguir?', 'El turno es el mismo para todo. Al elegir las manzanas, Lía renunció a tres verduras. Eso que dejas de hacer se llama costo de oportunidad.', 'ELECCION', 3);
INSERT INTO scenarios (id, misionId, orden, tipo, titulo, situacion, instruccion, explicacionFinal, conceptoId, dificultad) VALUES ('s18', 'm06', 2, 'COSTO_OPORTUNIDAD', 'Tablas o mesas', 'Nina puede sacar cuatro tablas en un turno, o montar dos mesas. Le han pedido dos tablas para arreglar un tejado.', 'Si hace dos tablas, ¿a cuántas mesas está renunciando?', 'La mitad del turno en tablas es media mesa menos… y como aquí hizo dos tablas, la renuncia fue una mesa entera.', 'ELECCION', 4);
INSERT INTO scenarios (id, misionId, orden, tipo, titulo, situacion, instruccion, explicacionFinal, conceptoId, dificultad) VALUES ('s19', 'm07', 0, 'COOPERACION', 'Tres mantas para el invierno', 'Hacen falta tres mantas antes de que lleguen las heladas. Nadie puede esquilar, tejer y repartir a la vez.', 'Coloca a cada habitante en una etapa y pulsa «Empezar el trabajo».', 'Cada uno hizo una parte y salieron las tres mantas. Por separado, haciendo los tres pasos solos, habrían salido muchas menos.', 'COOPERACION', 3);
INSERT INTO scenarios (id, misionId, orden, tipo, titulo, situacion, instruccion, explicacionFinal, conceptoId, dificultad) VALUES ('s20', 'm07', 1, 'COOPERACION', 'Nadie lleva la carreta', 'El pan sale del horno, pero se queda en la puerta: no hay quien lo lleve al mercado. Cuatro vecinos, tres etapas.', 'Reparte las tareas. Fíjate en qué etapa se queda corta.', 'El resultado no es la suma de lo que hace cada uno: es lo que permite la etapa más floja. Si nadie transporta, da igual cuánto pan salga del horno.', 'COOPERACION', 4);
INSERT INTO scenarios (id, misionId, orden, tipo, titulo, situacion, instruccion, explicacionFinal, conceptoId, dificultad) VALUES ('s21', 'm07', 2, 'CADENA', 'Del campo a la mesa', 'Tilo ha traído los pasos del pan revueltos en la bandolera.', 'Arrastra los pasos hasta ponerlos en el orden correcto.', 'Un producto pasa por muchas manos. Cada una se especializa en un paso, y por eso el Valle come pan todos los días.', 'COOPERACION', 2);
INSERT INTO scenarios (id, misionId, orden, tipo, titulo, situacion, instruccion, explicacionFinal, conceptoId, dificultad) VALUES ('s22', 'm08', 0, 'COOPERACION', 'La cooperativa se pone en marcha', 'Cuatro vecinos han decidido unir recursos para construir cuatro bancos para la plaza. Hay cuatro etapas y cuatro personas.', 'Coloca a cada uno donde más aporte.', 'Juntos consiguieron algo que ninguno podía hacer solo. Eso es una cooperativa: cada uno aporta lo suyo y el resultado es de todos.', 'COOPERACION', 4);
INSERT INTO scenarios (id, misionId, orden, tipo, titulo, situacion, instruccion, explicacionFinal, conceptoId, dificultad) VALUES ('s23', 'm08', 1, 'ESPECIALIZACION', 'El almacén de la cooperativa', 'La cooperativa quiere llenar el almacén antes del invierno: fruta, pan, tela y pescado.', 'Cuatro habitantes, un turno. Decide en qué se especializa cada uno.', 'Fíjate en Dani: produce más lana que tela, pero lo que hacía falta era tela. Especializarse es elegir bien, no elegir siempre el número más grande.', 'ESPECIALIZACION', 4);
INSERT INTO scenarios (id, misionId, orden, tipo, titulo, situacion, instruccion, explicacionFinal, conceptoId, dificultad) VALUES ('s24', 'm08', 2, 'INTERCAMBIO', 'Repartir lo de la cooperativa', 'Te han dado cuatro tarros de miel por tu trabajo. Necesitas una manta y pan.', 'Consigue las dos cosas intercambiando la miel.', 'Con un solo producto has cubierto dos necesidades distintas, porque cada vecino valoraba la miel por sus propios motivos.', 'INTERCAMBIO', 3);
INSERT INTO scenarios (id, misionId, orden, tipo, titulo, situacion, instruccion, explicacionFinal, conceptoId, dificultad) VALUES ('s25', 'm09', 0, 'INTERCAMBIO', 'Día de mercado', 'Traes cinco pescados del río. En la plaza hay tres puestos y todos miran tu cesta.', 'Consigue dos telas y dos puñados de clavos.', 'En el mercado no hay un precio escrito: hay gente con necesidades distintas. Por eso el mismo pescado vale cosas diferentes según con quién hables.', 'INTEGRACION', 4);
INSERT INTO scenarios (id, misionId, orden, tipo, titulo, situacion, instruccion, explicacionFinal, conceptoId, dificultad) VALUES ('s26', 'm09', 1, 'EVALUAR_OFERTA', 'Una manta por un clavo', 'Sofía tiene prisa y te propone un cambio rápido. Tú necesitas clavos, eso es cierto… pero mira bien qué te pide.', 'Decide si aceptas.', 'Necesitar algo no significa aceptar cualquier trato. Dos mantas son muchísimo trabajo; un puñado de clavos, bastante menos. Se puede pedir otra cosa.', 'INTEGRACION', 4);
INSERT INTO scenarios (id, misionId, orden, tipo, titulo, situacion, instruccion, explicacionFinal, conceptoId, dificultad) VALUES ('s27', 'm09', 2, 'ESCASEZ', 'Tres mantas y cinco casas', 'Solo han salido tres mantas del telar y el frío ya está en el Valle.', 'Reparte las tres mantas. Piensa quién no puede pasar la noche sin una.', 'Había varias formas correctas de repartir, pero todas empezaban por quien peor lo iba a pasar. Repartir bien no es dar lo mismo a todos.', 'INTEGRACION', 4);
INSERT INTO scenarios (id, misionId, orden, tipo, titulo, situacion, instruccion, explicacionFinal, conceptoId, dificultad) VALUES ('s28', 'm10', 0, 'ESPECIALIZACION', 'Preparar la feria', 'Mañana es la feria del Valle. Hay que llenar los puestos: fruta, verdura, pan y tela.', 'Cuatro habitantes, un turno. Que no falte nada.', 'Cuatro personas especializadas llenaron cuatro puestos en un solo turno. Haciendo cada uno de todo no habría llegado ni para dos.', 'INTEGRACION', 4);
INSERT INTO scenarios (id, misionId, orden, tipo, titulo, situacion, instruccion, explicacionFinal, conceptoId, dificultad) VALUES ('s29', 'm10', 1, 'COOPERACION', 'Montar los puestos', 'Los puestos de la feria no se montan solos: hay que traer tablas, armarlos y colocar la mercancía.', 'Coloca a los cuatro donde más aporten. Buscamos cinco puestos.', 'Ninguno de los cuatro podía montar un puesto entero solo. Coordinados salieron cinco.', 'INTEGRACION', 5);
INSERT INTO scenarios (id, misionId, orden, tipo, titulo, situacion, instruccion, explicacionFinal, conceptoId, dificultad) VALUES ('s30', 'm10', 2, 'INTERCAMBIO', 'Tu puesto en la feria', 'Has tejido cuatro cestas para vender. Quieres llevarte miel y queso a casa.', 'Consigue dos tarros de miel y un queso.', 'Produjiste algo que a otros les hacía falta, y con eso conseguiste lo que te faltaba a ti. Así funciona un mercado.', 'INTEGRACION', 4);
INSERT INTO scenarios (id, misionId, orden, tipo, titulo, situacion, instruccion, explicacionFinal, conceptoId, dificultad) VALUES ('s31', 'm10', 3, 'DECISION', 'El presupuesto del puesto', 'Para tu puesto tienes diez troncos y cuatro puñados de clavos. Ni uno más.', 'Elige como mucho dos cosas.', 'El mostrador grande y los bancos juntos no cabían en el presupuesto. Elegir uno significaba quedarse sin el otro.', 'ELECCION', 4);
INSERT INTO scenarios (id, misionId, orden, tipo, titulo, situacion, instruccion, explicacionFinal, conceptoId, dificultad) VALUES ('s32', 'm10', 4, 'ESCASEZ', 'Faltan cestas en la feria', 'Han quedado cinco cestas libres y cuatro puestos las piden. Entre todos necesitarían siete.', 'Reparte las cinco cestas.', 'Cinco cestas para siete peticiones. Otra vez escasez, y otra vez más de una manera razonable de repartir.', 'INTEGRACION', 4);
INSERT INTO scenarios (id, misionId, orden, tipo, titulo, situacion, instruccion, explicacionFinal, conceptoId, dificultad) VALUES ('s33', 'm11', 0, 'COSTO_OPORTUNIDAD', 'Bruno tiene que elegir', 'En un turno Bruno puede sacar seis verduras del huerto o tres sacos de trigo. Hoy le han pedido cuatro verduras.', 'Si dedica el turno a cuatro verduras, ¿a cuántos sacos de trigo renuncia?', 'Cuatro verduras son dos tercios del turno, y en ese tiempo habrían salido dos sacos de trigo. Esa es la parte que Bruno deja de hacer.', 'ELECCION', 4);
INSERT INTO scenarios (id, misionId, orden, tipo, titulo, situacion, instruccion, explicacionFinal, conceptoId, dificultad) VALUES ('s34', 'm11', 1, 'ESPECIALIZACION', 'Lía es mejor en todo… ¿y qué?', 'Lía recoge más manzanas Y más verduras que Bruno. Aun así, el Valle sale ganando si se reparten el trabajo.', 'Consigue seis manzanas y tres verduras entre los dos.', 'Aunque Lía es mejor en las dos cosas, cuando recoge verduras pierde muchas manzanas. A Bruno le cuesta menos dejar las manzanas. Por eso conviene que Lía vaya al frutal y Bruno al huerto.', 'ESPECIALIZACION', 5);
INSERT INTO scenarios (id, misionId, orden, tipo, titulo, situacion, instruccion, explicacionFinal, conceptoId, dificultad) VALUES ('s35', 'm11', 2, 'EVALUAR_OFERTA', 'Trigo por harina', 'Tienes cuatro sacos de trigo, pero en casa nadie sabe molerlos. Tomás te propone un cambio.', 'Piensa en el trabajo que hay detrás de cada cosa y decide.', 'El trigo sin moler no te sirve de nada. Tomás pone el molino y el trabajo; tú pones el grano. Los dos acabáis con algo que sí podéis usar.', 'INTERCAMBIO', 4);
INSERT INTO scenarios (id, misionId, orden, tipo, titulo, situacion, instruccion, explicacionFinal, conceptoId, dificultad) VALUES ('s36', 'm12', 0, 'DECISION', 'Antes de la primera nevada', 'Quedan ocho vellones de lana y seis troncos. El invierno no espera y no da tiempo a todo.', 'Elige como mucho dos cosas para el Valle.', 'No cabía todo. Elegir dos cosas significó dejar la tercera para más adelante, y eso también es una decisión económica.', 'ELECCION', 4);
INSERT INTO scenarios (id, misionId, orden, tipo, titulo, situacion, instruccion, explicacionFinal, conceptoId, dificultad) VALUES ('s37', 'm12', 1, 'ESCASEZ', 'Cuatro jarras de leche', 'Las cabras dan menos con el frío. Hoy solo hay cuatro jarras y se piden seis.', 'Reparte las cuatro jarras.', 'Con menos de lo que hace falta, lo primero es mirar quién no puede esperar. Lo demás se reparte como mejor parezca.', 'RECURSOS', 4);
INSERT INTO scenarios (id, misionId, orden, tipo, titulo, situacion, instruccion, explicacionFinal, conceptoId, dificultad) VALUES ('s38', 'm12', 2, 'COOPERACION', 'Cerrar el granero', 'Si entra nieve en el granero, se pierde la comida del invierno. Hay que cerrarlo hoy: cortar, clavar y subir las tablas al tejado.', 'Reparte las tres tareas entre Nina, Sofía y Rita.', 'Ninguno de los tres podía cerrar el granero solo. Repartidos, salió en una tarde.', 'COOPERACION', 4);
INSERT INTO scenarios (id, misionId, orden, tipo, titulo, situacion, instruccion, explicacionFinal, conceptoId, dificultad) VALUES ('s39', 'm13', 0, 'CADENA', 'La cadena de la tela', 'Una manta no aparece de la nada: empieza en el prado, con una oveja.', 'Pon los cinco pasos en orden.', 'Cada paso añade algo. Por eso una manta vale más que un vellón de lana: lleva mucho más trabajo dentro.', 'COOPERACION', 3);
INSERT INTO scenarios (id, misionId, orden, tipo, titulo, situacion, instruccion, explicacionFinal, conceptoId, dificultad) VALUES ('s40', 'm13', 1, 'CADENA', 'La mesa de la escuela', 'La escuela del Valle necesita una mesa nueva. En el bosque todavía es un árbol.', 'Ordena los pasos hasta que la mesa esté en la escuela.', 'Cuando cada persona se ocupa de un paso, el Valle consigue cosas que una sola persona tardaría semanas en terminar.', 'INTEGRACION', 3);
INSERT INTO scenarios (id, misionId, orden, tipo, titulo, situacion, instruccion, explicacionFinal, conceptoId, dificultad) VALUES ('s41', 'm14', 0, 'ESPECIALIZACION', 'Un turno para todo el Valle', 'Última tarea antes de que Tilo cierre el correo del año: el Valle necesita cinco cosas distintas en un solo turno.', 'Cinco habitantes, cinco oficios. Piénsalo bien.', 'Cinco personas, cinco tareas, un turno. Eso es una economía pequeña funcionando: cada uno hace lo suyo y entre todos sale lo que nadie podría solo.', 'INTEGRACION', 5);
INSERT INTO scenarios (id, misionId, orden, tipo, titulo, situacion, instruccion, explicacionFinal, conceptoId, dificultad) VALUES ('s42', 'm14', 1, 'INTERCAMBIO', 'La última cesta', 'Terminas el año con ocho manzanas y tres cosas por resolver: pan para la cena, una tela para la ventana y clavos para la puerta.', 'Consigue las tres cosas. Las manzanas justo dan.', 'Empezaste el Valle sin saber qué era un intercambio y acabas resolviendo tres a la vez. Eso es economía: gente que necesita cosas distintas poniéndose de acuerdo.', 'INTEGRACION', 5);

-- ----------------------------- insignias -----------------------------
INSERT INTO badges (id, nombre, descripcion, regla, meta, arteId) VALUES ('primer_trato', 'Primer trato', 'Cerraste tu primer intercambio en la plaza.', 'PRIMER_INTERCAMBIO', 1, 'insignia_apreton');
INSERT INTO badges (id, nombre, descripcion, regla, meta, arteId) VALUES ('gran_negociador', 'Buen negociador', 'Diez intercambios aceptados por tus vecinos.', 'INTERCAMBIOS_ACEPTADOS', 10, 'insignia_balanza');
INSERT INTO badges (id, nombre, descripcion, regla, meta, arteId) VALUES ('especialista', 'Especialista del Valle', 'Probaste seis repartos de trabajo distintos.', 'ESPECIALIZACIONES_PROBADAS', 6, 'insignia_azada');
INSERT INTO badges (id, nombre, descripcion, regla, meta, arteId) VALUES ('maestro_recursos', 'Maestro de recursos', 'Resolviste cinco repartos cuando no había para todos.', 'REPARTOS_RESUELTOS', 5, 'insignia_cesta');
INSERT INTO badges (id, nombre, descripcion, regla, meta, arteId) VALUES ('constructor_equipos', 'Constructor de equipos', 'Completaste cinco trabajos en equipo.', 'COOPERACIONES_COMPLETADAS', 5, 'insignia_engranaje');
INSERT INTO badges (id, nombre, descripcion, regla, meta, arteId) VALUES ('experto_decisiones', 'Experto en decisiones', 'Tomaste cinco decisiones con recursos limitados.', 'DECISIONES_TOMADAS', 5, 'insignia_bifurcacion');
INSERT INTO badges (id, nombre, descripcion, regla, meta, arteId) VALUES ('cooperador_valle', 'Cooperador del Valle', 'Terminaste diez misiones ayudando al pueblo.', 'MISIONES_COMPLETADAS', 10, 'insignia_manos');
INSERT INTO badges (id, nombre, descripcion, regla, meta, arteId) VALUES ('maestro_economia', 'Maestro de la economía', 'Completaste las catorce misiones del Valle.', 'MISIONES_COMPLETADAS', 14, 'insignia_corona');
INSERT INTO badges (id, nombre, descripcion, regla, meta, arteId) VALUES ('explorador_palabras', 'Explorador de palabras', 'Descubriste los siete conceptos del Diccionario.', 'CONCEPTOS_DESCUBIERTOS', 7, 'insignia_libro');
INSERT INTO badges (id, nombre, descripcion, regla, meta, arteId) VALUES ('almacenista', 'Almacenista', 'Guardaste doce objetos en el Almacén del Valle.', 'OBJETOS_COLECCIONADOS', 12, 'insignia_almacen');
INSERT INTO badges (id, nombre, descripcion, regla, meta, arteId) VALUES ('cientifico_valle', 'Curioso del laboratorio', 'Hiciste cinco experimentos en el Laboratorio del Valle.', 'EXPERIMENTOS_REALIZADOS', 5, 'insignia_matraz');

-- ------------------------- objetos del almacén ------------------------
INSERT INTO collection_items (id, nombre, familia, descripcion, comoSeConsigue, recursoId) VALUES ('col_manzana', 'Manzana del frutal', 'ALIMENTO', 'La primera cosecha de Lía.', 'Misión 1 · La primera cosecha', 'manzana');
INSERT INTO collection_items (id, nombre, familia, descripcion, comoSeConsigue, recursoId) VALUES ('col_verdura', 'Verdura del huerto', 'ALIMENTO', 'Lo que sale de la tierra de Bruno.', 'Misión 1 · La primera cosecha', 'verdura');
INSERT INTO collection_items (id, nombre, familia, descripcion, comoSeConsigue, recursoId) VALUES ('col_pan', 'Pan de Tomás', 'ELABORADO', 'El primer pan que conseguiste sin hornearlo tú.', 'Misión 2 · ¿Quién tiene lo que necesito?', 'pan');
INSERT INTO collection_items (id, nombre, familia, descripcion, comoSeConsigue, recursoId) VALUES ('col_herramienta', 'Herramienta de Sofía', 'HERRAMIENTA', 'Horas de taller convertidas en metal.', 'Misión 2 · ¿Quién tiene lo que necesito?', 'herramienta');
INSERT INTO collection_items (id, nombre, familia, descripcion, comoSeConsigue, recursoId) VALUES ('col_tabla', 'Tabla recta', 'ELABORADO', 'Un tronco al que Nina le vio la forma.', 'Misión 3 · Cada uno a lo suyo', 'tabla');
INSERT INTO collection_items (id, nombre, familia, descripcion, comoSeConsigue, recursoId) VALUES ('col_clavo', 'Puñado de clavos', 'HERRAMIENTA', 'Pequeños, y siempre faltan al final.', 'Misión 3 · Cada uno a lo suyo', 'clavo');
INSERT INTO collection_items (id, nombre, familia, descripcion, comoSeConsigue, recursoId) VALUES ('col_tela', 'Tela del telar', 'TEXTIL', 'Lana que ya sirve para algo.', 'Misión 4 · Intercambio de vecinos', 'tela');
INSERT INTO collection_items (id, nombre, familia, descripcion, comoSeConsigue, recursoId) VALUES ('col_trigo', 'Saco de trigo', 'MATERIA_PRIMA', 'Todavía no se puede comer.', 'Misión 5 · El problema del pan', 'trigo');
INSERT INTO collection_items (id, nombre, familia, descripcion, comoSeConsigue, recursoId) VALUES ('col_harina', 'Saco de harina', 'ELABORADO', 'El paso intermedio que casi nadie ve.', 'Misión 5 · El problema del pan', 'harina');
INSERT INTO collection_items (id, nombre, familia, descripcion, comoSeConsigue, recursoId) VALUES ('col_mesa', 'Mesa del Valle', 'ELABORADO', 'Ocho troncos y un día entero.', 'Misión 6 · La gran decisión', 'mesa');
INSERT INTO collection_items (id, nombre, familia, descripcion, comoSeConsigue, recursoId) VALUES ('col_silla', 'Silla de la plaza', 'ELABORADO', 'Más pequeña, y hacen falta varias.', 'Misión 6 · La gran decisión', 'silla');
INSERT INTO collection_items (id, nombre, familia, descripcion, comoSeConsigue, recursoId) VALUES ('col_lana', 'Vellón de lana', 'MATERIA_PRIMA', 'Recién esquilado, aún huele a prado.', 'Misión 7 · Juntos podemos', 'lana');
INSERT INTO collection_items (id, nombre, familia, descripcion, comoSeConsigue, recursoId) VALUES ('col_manta', 'Manta de invierno', 'TEXTIL', 'Cinco pasos y tres personas dentro.', 'Misión 7 · Juntos podemos', 'manta');
INSERT INTO collection_items (id, nombre, familia, descripcion, comoSeConsigue, recursoId) VALUES ('col_miel', 'Tarro de miel', 'ALIMENTO', 'Poca cantidad, mucha gente pidiéndola.', 'Misión 8 · La cooperativa', 'miel');
INSERT INTO collection_items (id, nombre, familia, descripcion, comoSeConsigue, recursoId) VALUES ('col_cesta', 'Cesta de mimbre', 'ELABORADO', 'Sin ella, media cosecha se queda en el campo.', 'Misión 8 · La cooperativa', 'cesta');
INSERT INTO collection_items (id, nombre, familia, descripcion, comoSeConsigue, recursoId) VALUES ('col_pescado', 'Pescado del río', 'ALIMENTO', 'Emi conoce cada recodo.', 'Misión 9 · El mercado del Valle', 'pescado');
INSERT INTO collection_items (id, nombre, familia, descripcion, comoSeConsigue, recursoId) VALUES ('col_queso', 'Queso curado', 'ELABORADO', 'Leche que supo esperar.', 'Misión 9 · El mercado del Valle', 'queso');
INSERT INTO collection_items (id, nombre, familia, descripcion, comoSeConsigue, recursoId) VALUES ('col_leche', 'Jarra de leche', 'ALIMENTO', 'De las cabras del prado alto.', 'Misión 10 · La gran feria', 'leche');
INSERT INTO collection_items (id, nombre, familia, descripcion, comoSeConsigue, recursoId) VALUES ('col_semilla', 'Puñado de semillas', 'MATERIA_PRIMA', 'La comida del año que viene.', 'Misión 10 · La gran feria', 'semilla');
INSERT INTO collection_items (id, nombre, familia, descripcion, comoSeConsigue, recursoId) VALUES ('col_puesto', 'Puesto de la feria', 'ELABORADO', 'Montado entre cuatro en una mañana.', 'Misión 10 · La gran feria', NULL);
INSERT INTO collection_items (id, nombre, familia, descripcion, comoSeConsigue, recursoId) VALUES ('col_martillo', 'Martillo de Sofía', 'HERRAMIENTA', 'El que usa cuando la cosa va en serio.', 'Misión 11 · El taller de los oficios', NULL);
INSERT INTO collection_items (id, nombre, familia, descripcion, comoSeConsigue, recursoId) VALUES ('col_farol', 'Farol del invierno', 'ELABORADO', 'Alumbra el granero cuando cae la nieve.', 'Misión 12 · El invierno se acerca', NULL);
INSERT INTO collection_items (id, nombre, familia, descripcion, comoSeConsigue, recursoId) VALUES ('col_mural', 'Mural de las cadenas', 'ELABORADO', 'El mapa de todo lo que pasa antes de que algo llegue.', 'Misión 13 · Las cadenas del Valle', NULL);
INSERT INTO collection_items (id, nombre, familia, descripcion, comoSeConsigue, recursoId) VALUES ('col_bandolera', 'Bandolera de Tilo', 'ELABORADO', 'Te la deja al marcharse. Ahora el correo es cosa tuya.', 'Misión 14 · El Valle entero', NULL);

-- ------------------------ diccionario del valle -----------------------
INSERT INTO glossary (id, termino, definicionInfantil, ejemplo, conceptoId, arteId, miniActividad) VALUES ('g_necesidad', 'Necesidad', 'Algo que te hace falta y ahora mismo no tienes.', 'Lía tiene manzanas de sobra, pero necesita pan para desayunar.', 'NECESIDADES', 'arte_necesidad', 'Mira la lista de un vecino y di qué le falta.');
INSERT INTO glossary (id, termino, definicionInfantil, ejemplo, conceptoId, arteId, miniActividad) VALUES ('g_recurso', 'Recurso', 'Cualquier cosa que sirve para producir o para vivir: madera, trigo, tiempo, manos.', 'Con diez troncos Nina puede hacer una mesa. Los troncos son un recurso.', 'RECURSOS', 'arte_recurso', 'Cuenta cuántos recursos distintos hay hoy en tu cesta.');
INSERT INTO glossary (id, termino, definicionInfantil, ejemplo, conceptoId, arteId, miniActividad) VALUES ('g_escasez', 'Escasez', 'Cuando hay menos de una cosa de la que la gente necesita.', 'Tres panes y cinco vecinos con hambre: eso es escasez.', 'RECURSOS', 'arte_escasez', 'Reparte tres panes entre cinco y mira a quién le toca esperar.');
INSERT INTO glossary (id, termino, definicionInfantil, ejemplo, conceptoId, arteId, miniActividad) VALUES ('g_produccion', 'Producción', 'Hacer que exista algo que antes no estaba.', 'Tomás no encuentra el pan: lo produce con harina, agua y un horno.', 'NECESIDADES', 'arte_produccion', 'Elige un oficio y mira cuánto sale en un turno.');
INSERT INTO glossary (id, termino, definicionInfantil, ejemplo, conceptoId, arteId, miniActividad) VALUES ('g_intercambio', 'Intercambio', 'Dar algo que tienes a cambio de algo que necesitas.', 'Tú das tres manzanas, Tomás te da dos panes. Los dos ganáis.', 'INTERCAMBIO', 'arte_intercambio', 'Busca en la plaza a alguien que necesite lo que te sobra.');
INSERT INTO glossary (id, termino, definicionInfantil, ejemplo, conceptoId, arteId, miniActividad) VALUES ('g_beneficio', 'Beneficio mutuo', 'Cuando las dos personas de un trato acaban mejor que antes.', 'Nina quería fruta y tú tablas. Después del trueque, los dos tenéis lo que buscabais.', 'INTERCAMBIO', 'arte_beneficio', 'Mira una propuesta y di qué gana cada uno.');
INSERT INTO glossary (id, termino, definicionInfantil, ejemplo, conceptoId, arteId, miniActividad) VALUES ('g_especializacion', 'Especialización', 'Dedicarse a una sola tarea en lugar de hacer un poco de todo.', 'Lía solo recoge manzanas y Tomás solo hornea. Entre los dos sale más.', 'ESPECIALIZACION', 'arte_especializacion', 'Prueba el mismo turno con y sin especializar y compara.');
INSERT INTO glossary (id, termino, definicionInfantil, ejemplo, conceptoId, arteId, miniActividad) VALUES ('g_ventaja', 'Quién debería hacer qué', 'No siempre produce algo quien mejor lo hace, sino quien menos deja de hacer al dedicarse a ello.', 'Lía es mejor en todo, pero si va al huerto pierde muchas manzanas. Mejor que vaya al frutal.', 'ESPECIALIZACION', 'arte_ventaja', 'Compara cuánto pierde cada uno al cambiar de tarea.');
INSERT INTO glossary (id, termino, definicionInfantil, ejemplo, conceptoId, arteId, miniActividad) VALUES ('g_cooperacion', 'Cooperación', 'Repartirse las partes de un trabajo para llegar donde solos no llegaríamos.', 'Uno esquila, otro teje y otro reparte. Así salen las tres mantas.', 'COOPERACION', 'arte_cooperacion', 'Coloca a cada habitante en una etapa y mira el resultado.');
INSERT INTO glossary (id, termino, definicionInfantil, ejemplo, conceptoId, arteId, miniActividad) VALUES ('g_cadena', 'Cadena de producción', 'Los pasos por los que pasa algo antes de llegar a quien lo necesita.', 'Trigo → harina → pan → carreta → mercado.', 'COOPERACION', 'arte_cadena', 'Ordena los pasos del pan.');
INSERT INTO glossary (id, termino, definicionInfantil, ejemplo, conceptoId, arteId, miniActividad) VALUES ('g_eleccion', 'Elección', 'Quedarse con una opción cuando no se pueden tener todas.', 'Con diez troncos: una mesa, o una silla y tres cestas. No las dos cosas.', 'ELECCION', 'arte_eleccion', 'Gasta diez troncos y mira qué te queda.');
INSERT INTO glossary (id, termino, definicionInfantil, ejemplo, conceptoId, arteId, miniActividad) VALUES ('g_costo', 'Costo de oportunidad', 'Lo que dejas de hacer cuando eliges otra cosa.', 'Si Lía pasa el turno recogiendo seis manzanas, deja de cuidar tres verduras.', 'ELECCION', 'arte_costo', 'Mueve el reparto del turno y mira los dos números a la vez.');
INSERT INTO glossary (id, termino, definicionInfantil, ejemplo, conceptoId, arteId, miniActividad) VALUES ('g_mercado', 'Mercado', 'El sitio donde la gente que necesita cosas distintas se pone de acuerdo.', 'En la plaza del Valle nadie manda: cada uno propone y decide.', 'INTEGRACION', 'arte_mercado', 'Da una vuelta por el mercado y mira quién necesita qué.');

-- =====================================================================
-- ESTADO DE EJEMPLO (así queda la base tras un rato jugando)
-- =====================================================================
INSERT INTO profile (id, alias, avatarId, onboardingHecho, sonidoActivo, vibracionActiva, textoGrande, creadoMillis) VALUES (1, 'Tuli', 'avatar_3', 1, 1, 1, 0, 1735689600000);

INSERT INTO scenario_attempts (escenarioId, misionId, conceptoId, logrado, numeroDeIntento, fechaMillis) VALUES ('s01', 'm01', 'NECESIDADES', 1, 1, 1735689700000);
INSERT INTO scenario_attempts (escenarioId, misionId, conceptoId, logrado, numeroDeIntento, fechaMillis) VALUES ('s02', 'm01', 'NECESIDADES', 0, 1, 1735689800000);
INSERT INTO scenario_attempts (escenarioId, misionId, conceptoId, logrado, numeroDeIntento, fechaMillis) VALUES ('s02', 'm01', 'NECESIDADES', 1, 2, 1735689900000);
INSERT INTO scenario_attempts (escenarioId, misionId, conceptoId, logrado, numeroDeIntento, fechaMillis) VALUES ('s03', 'm01', 'RECURSOS', 1, 1, 1735690000000);

INSERT INTO mission_progress (misionId, estado, intentosTotales, sinFallos, actualizadoMillis) VALUES ('m01', 'COMPLETADO', 4, 0, 1735690000000);

INSERT INTO trades (escenarioId, proponenteId, receptorId, entrega, pide, aceptado, motivo, fechaMillis) VALUES ('s04', 'jugador', 'tomas', 'manzana:1', 'pan:2', 0, 'DESEQUILIBRIO', 1735690100000);
INSERT INTO trades (escenarioId, proponenteId, receptorId, entrega, pide, aceptado, motivo, fechaMillis) VALUES ('s04', 'jugador', 'tomas', 'manzana:3', 'pan:2', 1, NULL, 1735690200000);

INSERT INTO specialization_runs (escenarioId, plan, produccionTotal, valorTotal, cumplioObjetivo, fechaMillis) VALUES ('s03', 'bruno=verdura|lia=manzana', 'manzana:6|verdura:6', 12, 1, 1735690300000);

INSERT INTO cooperation_runs (escenarioId, plan, resultado, objetivo, resultadoSinCooperar, completado, fechaMillis) VALUES ('s19', 'dani=tejer|lia=esquilar|rita=repartir', 3, 3, 2, 1, 1735690400000);

INSERT INTO allocation_runs (escenarioId, recursoId, disponible, reparto, valido, fechaMillis) VALUES ('s13', 'pan', 3, 'bruno:1|lia:2', 1, 1735690500000);

INSERT INTO decision_runs (escenarioId, seleccion, renuncias, alcanza, fechaMillis) VALUES ('s16', 'silla|cesta', 'Una mesa grande', 1, 1735690600000);

INSERT INTO user_collection (objetoId, fechaMillis) VALUES ('col_manzana', 1735690000000);
INSERT INTO user_collection (objetoId, fechaMillis) VALUES ('col_verdura', 1735690000000);
INSERT INTO user_badges (insigniaId, fechaMillis) VALUES ('primer_trato', 1735690200000);
INSERT INTO discovered_concepts (conceptoId, fechaMillis) VALUES ('NECESIDADES', 1735689700000);
INSERT INTO discovered_concepts (conceptoId, fechaMillis) VALUES ('RECURSOS', 1735690000000);
INSERT INTO warehouse (recursoId, cantidad) VALUES ('manzana', 1);
INSERT INTO warehouse (recursoId, cantidad) VALUES ('verdura', 1);

INSERT INTO experiments (etiqueta, habitantes, turnos, modo, permiteIntercambio, ponenEnComun, produccionTotal, valorTotal, intercambios, necesidadesCubiertas, necesidadesTotales, fechaMillis) VALUES ('experimento', 4, 2, 'TODOS_DE_TODO', 0, 0, 'harina:2|madera:2|manzana:2|pan:2|tabla:2|verdura:2', 20, 0, 0, 8, 1735690700000);
INSERT INTO experiments (etiqueta, habitantes, turnos, modo, permiteIntercambio, ponenEnComun, produccionTotal, valorTotal, intercambios, necesidadesCubiertas, necesidadesTotales, fechaMillis) VALUES ('experimento', 4, 2, 'CADA_UNO_LO_SUYO', 0, 0, 'manzana:12|pan:10|silla:6|verdura:12', 62, 0, 0, 8, 1735690800000);

INSERT INTO daily_challenge (diaIndice, escenarioId, completado, fechaMillis) VALUES (20089, 's10', 1, 1735690900000);

